---
version: '2'
services:
  db:
    image: influxdb:1.8
    container_name: speedtest_db
    volumes:
      - "./data/influxdb/:/var/lib/influxdb"
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - ./env/db.env
  web:
    build: ./speedweb
    container_name: speedtest_web
    ports:
      - "3000:3000"
    links:
      - db:db
    env_file:
      - ./env/web.env
  testing:
    build: ./speedtest
    container_name: speedtest_cli
    links:
      - db:db
    env_file:
      - ./env/testing.env
